In [2]:
import numpy as np

In [3]:
def x1_n(x1,x2):
    return x1 + x2

def x2_n(x2, u):
    return x2 + u

In [10]:
u = np.array([-1,0,1])
state = np.array([
                [0,2],[1,2],[2,2],
                [0,1],[1,1],[2,1],
                [0,0],[1,0],[2,0] ])


state_n = {str(i) : np.array( [[x1_n(i[0],i[1]), x2_n(i[1], u[0])],
                                [x1_n(i[0],i[1]), x2_n(i[1], u[1])],
                                [x1_n(i[0],i[1]), x2_n(i[1], u[2])]] ) for i in state}
for key in state_n:
    print("key:  ")
    print(key)
    print("value: ")
    print(state_n[key])

key:  
[0 2]
value: 
[[2 1]
 [2 2]
 [2 3]]
key:  
[1 2]
value: 
[[3 1]
 [3 2]
 [3 3]]
key:  
[2 2]
value: 
[[4 1]
 [4 2]
 [4 3]]
key:  
[0 1]
value: 
[[1 0]
 [1 1]
 [1 2]]
key:  
[1 1]
value: 
[[2 0]
 [2 1]
 [2 2]]
key:  
[2 1]
value: 
[[3 0]
 [3 1]
 [3 2]]
key:  
[0 0]
value: 
[[ 0 -1]
 [ 0  0]
 [ 0  1]]
key:  
[1 0]
value: 
[[ 1 -1]
 [ 1  0]
 [ 1  1]]
key:  
[2 0]
value: 
[[ 2 -1]
 [ 2  0]
 [ 2  1]]


In [16]:
starting = np.array([
    -10,50
])
ending = np.array([
    30,31
])

u1 = ending[0] - starting[0] - 2*starting[1]
u2 = ending[1] - starting[1] - u1
s1x = x1_n(starting[0],starting[1])
s1y = x2_n(starting[1],u1)
mid = np.array([s1x,s1y])
end = np.array([x1_n(s1x,s1y),x2_n(s1y,u2)])
print("start")
print(starting)
print("mid")
print(mid)
print("end")
print(end)
print("goal")
print(ending)

start
[-10  50]
mid
[ 40 -10]
end
[30 31]
goal
[30 31]
